Univa git 007 "No Action Taken"
jaycorpstudios/cinema-js pull request #13
Opened 2018-01-19 02:58 UTC by NobleSix1010

Nothing to do here... git 008 is the actual ticket

2018-01-19 04:14 UTC, jaycorpstudios requested changes
Can you take a look at the files again? It seems like you only deleted one line and that's it 😦

2018-01-20 00:40 UTC, NobleSix1010 commented
Sorry Jay, I thought you told me that the ticket git 008 (TO DO: 8) was supposed to be the one solving the 007's problem :S, unless there was actually something I should've done, because there was a method called orderByStars() and it has the movie.star and .sort() instruction that the person assigned to the ticket 8 should do. That's the reason why I only deleted the line that contained the "TO DO: 7..". If there was actually something I missed, please let me know so that  I can finish it.


Thanks,

Iván Ruiz Ramírez


________________________________
From: Juan José Benítez (Jay) <notifications@github.com>
Sent: Thursday, January 18, 2018 10:14 PM
To: jaycorpstudios/cinema-js
Cc: Ivan; Author
Subject: Re: [jaycorpstudios/cinema-js] Univa git 007 "No Action Taken" (#13)


@jaycorpstudios requested changes on this pull request.

Can you take a look at the files again? It seems like you only deleted one line and that's it 😦

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/jaycorpstudios/cinema-js/pull/13#pullrequestreview-90008538>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AXyWyedHMbTD9QiDxzw2BF6_b2vvebjFks5tMBacgaJpZM4Rj6yy>.

2018-01-23 04:27 UTC, jaycorpstudios commented
Ok gotcha, I think the problem is that I forgot to delete/modify those line in order to add "something to do" but that's ok. I'll approve this and then you can merge it to develop, tomorrow we'll explore what happen once the branch is merge and how to retrieve those changes from develop, and even better.. how to fix a merge conflict.

2018-01-23 04:31 UTC, jaycorpstudios approved these changes

2018-01-24 01:19 UTC, merged